/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ChatMessage = {
  _type: "chatMessage";
  from?: "guest" | "ai";
  name?: string;
  text?: string;
};

export type FaqItem = {
  _type: "faqItem";
  q?: string;
  a?: string;
};

export type Testimonial = {
  _type: "testimonial";
  quote?: string;
  name?: string;
  org?: string;
  initials?: string;
  avatar?: "brand" | "amber" | "teal";
};

export type Step = {
  _type: "step";
  title?: string;
  body?: string;
  accent?: "brand" | "amber";
};

export type IconCard = {
  _type: "iconCard";
  icon?:
    | "message"
    | "user"
    | "calendar"
    | "checkCircle"
    | "refresh"
    | "help"
    | "mailOpen"
    | "clock"
    | "calendarX"
    | "calendarCheck"
    | "card"
    | "chart"
    | "buildings"
    | "bell";
  title?: string;
  body?: string;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  href?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  noindex?: boolean;
};

export type Cta = {
  _type: "cta";
  headingTop?: string;
  headingBottom?: string;
  body?: string;
  trust?: string;
};

export type Faq = {
  _type: "faq";
  eyebrow?: string;
  heading?: string;
  items?: Array<
    {
      _key: string;
    } & FaqItem
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SocialProof = {
  _type: "socialProof";
  heading?: string;
  intro?: string;
  photos?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
  logos?: Array<string>;
};

export type Features = {
  _type: "features";
  eyebrow?: string;
  heading?: string;
  items?: Array<
    {
      _key: string;
    } & IconCard
  >;
};

export type HowItWorks = {
  _type: "howItWorks";
  eyebrow?: string;
  heading?: string;
  steps?: Array<
    {
      _key: string;
    } & Step
  >;
};

export type AiSpotlight = {
  _type: "aiSpotlight";
  eyebrow?: string;
  heading?: string;
  intro?: string;
  chat?: Array<
    {
      _key: string;
    } & ChatMessage
  >;
  capabilities?: Array<
    {
      _key: string;
    } & IconCard
  >;
};

export type Problem = {
  _type: "problem";
  eyebrow?: string;
  heading?: string;
  intro?: string;
  cards?: Array<
    {
      _key: string;
    } & IconCard
  >;
};

export type Hero = {
  _type: "hero";
  badge?: string;
  subtitle?: string;
  trust?: string;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & Problem)
  | ({
      _key: string;
    } & AiSpotlight)
  | ({
      _key: string;
    } & HowItWorks)
  | ({
      _key: string;
    } & Features)
  | ({
      _key: string;
    } & SocialProof)
  | ({
      _key: string;
    } & Faq)
  | ({
      _key: string;
    } & Cta)
>;

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  nav?: {
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    cta?: NavLink;
  };
  footer?: {
    tagline?: string;
    links?: Array<
      {
        _key: string;
      } & NavLink
    >;
    cta?: NavLink;
    copyright?: string;
  };
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  seo?: Seo;
  pageBuilder?: PageBuilder;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ChatMessage
  | FaqItem
  | Testimonial
  | Step
  | IconCard
  | NavLink
  | Seo
  | Cta
  | Faq
  | SanityImageAssetReference
  | SocialProof
  | Features
  | HowItWorks
  | AiSpotlight
  | Problem
  | Hero
  | PageBuilder
  | SiteSettings
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/cms/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,  title,  "slug": slug.current,  seo{ title, description, noindex },  pageBuilder[]{ ... }}
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  seo: {
    title: string | null;
    description: string | null;
    noindex: boolean | null;
  } | null;
  pageBuilder: Array<
    | {
        _key: string;
        _type: "aiSpotlight";
        eyebrow?: string;
        heading?: string;
        intro?: string;
        chat?: Array<
          {
            _key: string;
          } & ChatMessage
        >;
        capabilities?: Array<
          {
            _key: string;
          } & IconCard
        >;
      }
    | {
        _key: string;
        _type: "cta";
        headingTop?: string;
        headingBottom?: string;
        body?: string;
        trust?: string;
      }
    | {
        _key: string;
        _type: "faq";
        eyebrow?: string;
        heading?: string;
        items?: Array<
          {
            _key: string;
          } & FaqItem
        >;
      }
    | {
        _key: string;
        _type: "features";
        eyebrow?: string;
        heading?: string;
        items?: Array<
          {
            _key: string;
          } & IconCard
        >;
      }
    | {
        _key: string;
        _type: "hero";
        badge?: string;
        subtitle?: string;
        trust?: string;
      }
    | {
        _key: string;
        _type: "howItWorks";
        eyebrow?: string;
        heading?: string;
        steps?: Array<
          {
            _key: string;
          } & Step
        >;
      }
    | {
        _key: string;
        _type: "problem";
        eyebrow?: string;
        heading?: string;
        intro?: string;
        cards?: Array<
          {
            _key: string;
          } & IconCard
        >;
      }
    | {
        _key: string;
        _type: "socialProof";
        heading?: string;
        intro?: string;
        photos?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
          _key: string;
        }>;
        testimonials?: Array<
          {
            _key: string;
          } & Testimonial
        >;
        logos?: Array<string>;
      }
  > | null;
} | null;

// Source: lib/cms/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  nav{ links[]{ label, href }, cta{ label, href } },  footer{ tagline, links[]{ label, href }, cta{ label, href }, copyright }}
export type SITE_SETTINGS_QUERY_RESULT = {
  nav: {
    links: Array<{
      label: string | null;
      href: string | null;
    }> | null;
    cta: {
      label: string | null;
      href: string | null;
    } | null;
  } | null;
  footer: {
    tagline: string | null;
    links: Array<{
      label: string | null;
      href: string | null;
    }> | null;
    cta: {
      label: string | null;
      href: string | null;
    } | null;
    copyright: string | null;
  } | null;
} | null;

// Source: lib/cms/queries.ts
// Variable: SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{  "slug": slug.current,  "updatedAt": _updatedAt}
export type SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
  updatedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "page" && slug.current == $slug][0]{\n  _id,\n  title,\n  "slug": slug.current,\n  seo{ title, description, noindex },\n  pageBuilder[]{ ... }\n}': PAGE_QUERY_RESULT;
    '*[_type == "siteSettings"][0]{\n  nav{ links[]{ label, href }, cta{ label, href } },\n  footer{ tagline, links[]{ label, href }, cta{ label, href }, copyright }\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "page" && defined(slug.current)]{\n  "slug": slug.current,\n  "updatedAt": _updatedAt\n}': SLUGS_QUERY_RESULT;
  }
}
